//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogCar()
        {
            this.RentalCars = new HashSet<RentalCar>();
        }
    
        public int CatalogCarId { get; set; }
        public string CatalogCarBrand { get; set; }
        public string CatalogCarModel { get; set; }
        public int CountryCarId { get; set; }
        public Nullable<int> ClassCarId { get; set; }
        public int StatusCatalogCarId { get; set; }
        public int CatalogCarMileage { get; set; }
        public int CatalogCarPricePerDay { get; set; }
        public string CatalogCarImageName { get; set; }
    
        public virtual ClassCar ClassCar { get; set; }
        public virtual CountryCar CountryCar { get; set; }
        public virtual StatusCatalogCar StatusCatalogCar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalCar> RentalCars { get; set; }
    }
}
