//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.AdditionalServicesOnOrders = new HashSet<AdditionalServicesOnOrder>();
        }
    
        public int DriverId { get; set; }
        public string DriverFullName { get; set; }
        public decimal DriverDriverLicenseNumber { get; set; }
        public int DriverPricePerDay { get; set; }
        public System.TimeSpan DriverWorkBegin { get; set; }
        public System.TimeSpan DriverWorkEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalServicesOnOrder> AdditionalServicesOnOrders { get; set; }
    }
}
