//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int FineId { get; set; }
        public int RentalCarId { get; set; }
        public int NameFineId { get; set; }
        public System.DateTime FineReceiptDate { get; set; }
        public int FinePrice { get; set; }
    
        public virtual NameFine NameFine { get; set; }
        public virtual RentalCar RentalCar { get; set; }
    }
}
