//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENTAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnCarHaveDamage
    {
        public int RentalCarId { get; set; }
        public int TypeCarDamageId { get; set; }
        public int ReturnCarHaveDamageAmount { get; set; }
    
        public virtual RentalCar RentalCar { get; set; }
        public virtual TypeCarDamage TypeCarDamage { get; set; }
    }
}
